keys:
  - &chunk age1eg6sxflw6l44fp20sl068sampwd95fm0mnh4ssegrhtktgm50ptqcuspyn
  - &yt age1sy0at69err83qyml2vqu8xvwjccfws447aaadfvacj2qluw3p45s2mtrw8
  - &cy age10h6pg5qdpc4t0rpmksfv788a57f04n83zgqaezkjjn65nkhv547s0vxfdn
  - &titan age12w2xgh4nxhrrggrtcnu75wgukqnayzhfd2azkhukl6u8xqxsqvtsa4lmhl
creation_rules:
  - path_regex: secrets/de3911/yt.yaml
    key_groups:
      - age:
          - *yt
          - *cy
  - path_regex: secrets/de3911/chunk.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/de3911/titan.yaml
    key_groups:
      - age:
          - *titan
          - *cy
  - path_regex: secrets/services/ntfy.yaml
    key_groups:
      - age:
          - *chunk
          - *yt
          - *titan
          - *cy
  - path_regex: secrets/restic/yt.yaml
    key_groups:
      - age:
          - *yt
          - *cy
  - path_regex: secrets/borg/yt.yaml
    key_groups:
      - age:
          - *yt
          - *cy
  - path_regex: secrets/borg/chunk.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/borg/titan.yaml
    key_groups:
      - age:
          - *titan
          - *cy
  - path_regex: secrets/wireguard/yt.yaml
    key_groups:
      - age:
          - *yt
          - *cy
  - path_regex: secrets/wireguard/chunk.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/services/caddy.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
          - *titan
  - path_regex: secrets/services/hedgedoc.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/services/miniflux.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/services/gitlab.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/services/vaultwarden.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/rclone.yaml
    key_groups:
      - age:
          - *chunk
          - *yt
          - *cy
  - path_regex: secrets/newsboat.yaml
    key_groups:
      - age:
          - *yt
          - *cy
  - path_regex: secrets/services/attic.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/services/garage.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/services/tailscale.yaml
    key_groups:
      - age:
          - *chunk
          - *cy
  - path_regex: secrets/yt/(.*).yaml$
    key_groups:
      - age:
          - *yt
          - *cy
