name: build and cache packages
on:
  workflow_dispatch:
    inputs:
      package:
        description: "package to build"
        required: false
        type: string

env:
  TERM: ansi
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_ENDPOINT_URL: https://s3.cy7.sh
  RUST_LOG: nixcp=trace

jobs:
  build-packages:
    strategy:
      fail-fast: false
      matrix:
        package:
          - ${{ inputs.package }}
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13
    runs-on: ${{ matrix.os }}

    steps:
      - name: setup binary cache key
        run: echo -n "${{ secrets.NIX_CACHE_SECRET_KEY }}" | xxd -p -r > ${{ runner.temp }}/cache-priv-key.pem

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          enable_kvm: true
          extra_nix_config: |
            show-trace = true
            experimental-features = nix-command flakes
            accept-flake-config = true
            system-features = nixos-test benchmark big-parallel kvm
            secret-key-files = ${{ runner.temp }}/cache-priv-key.pem
            extra-substituters = https://nixcache.cy7.sh https://cache.lix.systems
            extra-trusted-public-keys = nixcache.cy7.sh:DN3d1dt0wnXfTH03oVmTee4KgmdNdB0NY3SuzA8Fwx8= cache.lix.systems:aBnZUw8zA7H35Cz2RyKFVs3H4PlGTLawyY5KRbvJR8o=

      - name: Install Lix
        run: |
          sudo --preserve-env=PATH $(which nix) run \
          'git+https://git.lix.systems/lix-project/lix?ref=refs/tags/2.92.0' -- \
          upgrade-nix
          nix --version

      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: nix build -L ${{ matrix.package }}

      - name: cache result
        # https://stackoverflow.com/a/58859404
        if: '!cancelled()'
        run: |
          nix run github:cything/nixcp/2025-04-12 -- \
            push \
            --bucket nixcache \
            --signing-key ${{ runner.temp }}/cache-priv-key.pem \
            -u https://nix-community.cachix.org \
            "${{ matrix.package }}"

      - name: prepare tarball to upload
        run: nix run github:nixos/nixpkgs#gnutar hcvf result.tar result

      - name: upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: result.tar
          if-no-files-found: error
