name: build and cache packages
on:
  workflow_dispatch:
    inputs:
      package:
        description: "package to build"
        required: false
        type: string
jobs:
  build-packages:
    strategy:
      matrix:
        package:
          - ${{ inputs.package }}
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest
          - macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Sync repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: cachix/cachix-action@v14
        with:
          name: cything
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          useDaemon: false
          installCommand: nix profile install nixpkgs#cachix

      - run: nix build -L ${{ matrix.package }}
